In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_cleaning import load_trade
from refreshTime import refresh_time, test_date, resample,synchro_data,harmoniz_data
from Clustering import get_clusters
from GMVP import get_GMVP,Louvain_GMVP,get_profit_vanilla

In [2]:
Date = pd.bdate_range('2010-01-01','2010-12-31')
Market_name = np.array(['AAPL.OQ','AMGN.OQ','AXP.N','BA.N','CAT.N','CSCO.OQ','CVX.N','DOW.N','GS.N','SPY.P','UTX.N','V.N','WMT.N'])

#folder_path = 'D:/GitHub/ML_For_Finance/big data/data/data/'

folder_path ='D:/GitHub/ML for Finance project/ML_For_Finance/big data/Data/data/'
#folder_path = '/Users/franckatteaka/Desktop/cours/Semester III/Financial big data/high freq data/'

In [3]:
aapl = load_trade(Market_name[0],Date[7],folder_path,is_compressed = True)
amgn = load_trade(Market_name[1],Date[7],folder_path,is_compressed = True)
axpn = load_trade(Market_name[2],Date[7],folder_path,is_compressed = True)

In [4]:
test1= [aapl.iloc[:1000],amgn.iloc[:1000],axpn.iloc[:1000]]

In [3]:
test2=[]
for i in range(len(Market_name)):
    data0=load_trade(Market_name[i],Date[101],folder_path,is_compressed = True)
    test2.append(data0)

In [4]:
data1=harmoniz_data(test2)

D:\GitHub\ML for Finance project\ML_For_Finance\big data\Code\refreshTime.py:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dates = np.array([df.index.drop_duplicates(keep = 'last') for df in dfs])
D:\GitHub\ML for Finance project\ML_For_Finance\big data\Code\refreshTime.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dates = np.array([date[np.where(date > tau[-1])[0]] for date in dates ])


In [5]:
louvain_test = Louvain_GMVP(data1)
louvain_test.get_return(test2,Market_name)
louvain_test.retour

array([-0.00718018])

In [6]:
vanilla_weight,_,_= get_GMVP(data1)
get_profit_vanilla(vanilla_weight,test2)

array([0.01109193])

In [11]:
louvain_test = Louvain_GMVP(data1)
louvain_test.get_profit(test2,Market_name)
louvain_test.profit

array([0.08038539])

In [12]:
vanilla_weight,_,_= get_GMVP(data1)
get_profit_vanilla(vanilla_weight,test2)

array([0.27925532])

In [14]:
sum(vanilla_weight)

1.0000000000000002

In [17]:
np.sum(louvain_test.w_louvain)

ValueError: could not broadcast input array from shape (8) into shape (1)