In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from data_cleaning import load_trade
from refreshTime import refresh_time, test_date, resample,synchro_data,harmoniz_data
from Clustering import get_clusters
from GMVP import get_GMVP,Louvain_GMVP,get_profit_vanilla

In [2]:
Date = pd.bdate_range('2010-01-01','2010-12-31')
Market_name = np.array(['AAPL.OQ','AMGN.OQ','AXP.N','BA.N','CAT.N','CSCO.OQ','CVX.N','DOW.N','GS.N','SPY.P','UTX.N','V.N','WMT.N'])

#folder_path = 'D:/GitHub/ML_For_Finance/big data/data/data/'

folder_path ='D:/GitHub/ML for Finance project/ML_For_Finance/big data/Data/data/'
#folder_path = '/Users/franckatteaka/Desktop/cours/Semester III/Financial big data/high freq data/'

In [3]:
aapl = load_trade(Market_name[0],Date[7],folder_path,is_compressed = True)
amgn = load_trade(Market_name[1],Date[7],folder_path,is_compressed = True)
axpn = load_trade(Market_name[2],Date[7],folder_path,is_compressed = True)

In [4]:
test1= [aapl.iloc[:1000],amgn.iloc[:1000],axpn.iloc[:1000]]

In [3]:
test2=[]
for i in range(len(Market_name)):
    data0=load_trade(Market_name[i],Date[101],folder_path,is_compressed = True)
    test2.append(data0)

In [4]:
data1=harmoniz_data(test2)

D:\GitHub\ML for Finance project\ML_For_Finance\big data\Code\refreshTime.py:33: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dates = np.array([df.index.drop_duplicates(keep = 'last') for df in dfs])
D:\GitHub\ML for Finance project\ML_For_Finance\big data\Code\refreshTime.py:43: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  dates = np.array([date[np.where(date > tau[-1])[0]] for date in dates ])


In [5]:
louvain_test = Louvain_GMVP(data1)
louvain_test.get_return(test2,Market_name)
louvain_test.retour

array([-0.00718018])

In [6]:
vanilla_weight,_,_= get_GMVP(data1)
get_profit_vanilla(vanilla_weight,test2)

array([0.01109193])

In [11]:
louvain_test = Louvain_GMVP(data1)
louvain_test.get_profit(test2,Market_name)
louvain_test.profit

array([0.08038539])

In [12]:
vanilla_weight,_,_= get_GMVP(data1)
get_profit_vanilla(vanilla_weight,test2)

array([0.27925532])

In [14]:
sum(vanilla_weight)

1.0000000000000002

In [11]:
Date

DatetimeIndex(['2010-01-01', '2010-01-04', '2010-01-05', '2010-01-06',
               '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
               '2010-01-13', '2010-01-14',
               ...
               '2010-12-20', '2010-12-21', '2010-12-22', '2010-12-23',
               '2010-12-24', '2010-12-27', '2010-12-28', '2010-12-29',
               '2010-12-30', '2010-12-31'],
              dtype='datetime64[ns]', length=261, freq='B')

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from back_test import daily_back_testing

In [2]:
Date = pd.bdate_range('2010-01-01','2010-12-31')
Market_name = np.array(['AAPL.OQ','AMGN.OQ','AXP.N','BA.N','CAT.N','CSCO.OQ','CVX.N','DOW.N','GS.N','SPY.P','UTX.N','V.N','WMT.N'])

#folder_path = 'D:/GitHub/ML_For_Finance/big data/data/data/'

folder_path ='D:/GitHub/ML for Finance project/ML_For_Finance/big data/Data/data/'
#folder_path = '/Users/franckatteaka/Desktop/cours/Semester III/Financial big data/high freq data/'

In [3]:
nday_init=40
nday_end=70
backtesting1=daily_back_testing(Market_name,folder_path,Date[nday_init])


In [ ]:
l=nday_end-nday_init
for i in range(nday_init+1,nday_end+1):
    backtesting1.daily_update(Date[i])
    print('avancement : %f '%((i-nday_init)/l))

avancement : 0.033333 
avancement : 0.066667 
avancement : 0.100000 
avancement : 0.133333 
avancement : 0.166667 
avancement : 0.200000 
avancement : 0.233333 
avancement : 0.266667 
avancement : 0.300000 
avancement : 0.333333 
avancement : 0.366667 
avancement : 0.400000 
avancement : 0.433333 
avancement : 0.466667 
avancement : 0.500000 
avancement : 0.533333 
avancement : 0.566667 
avancement : 0.600000 
avancement : 0.633333 
avancement : 0.666667 
avancement : 0.700000 
avancement : 0.733333 


In [ ]:
backtesting1.plot_value()

In [ ]:
backtesting1.V_louvain

In [ ]:
backtesting1.V_vanilla

In [ ]:
backtesting1.correlation/backtesting1.nombre_test

In [ ]:
backtesting1.louvain_cluster/backtesting1.nombre_test

In [ ]:
backtesting1.louvain_return

In [ ]:
backtesting1.vanilla_return